title: Fair Division Algorithms
description: An interactive educational platform developed by Amaan Khan and Dr. Ron Cytron.  Washington University in St. Louis received financial support from Mozilla Responsible Computer Science for this project.

baseurl: "/fair-division-algorithms"
url: "https://amaan-19.github.io"

# Ensure proper permalink structure
permalink: pretty

markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
highlighter: rouge

# Sass/SCSS Configuration
sass:
  sass_dir: assets/css
  style: compressed
  load_paths:
    - assets/css
    - assets/css/settings
    - assets/css/tools
    - assets/css/components

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-sass-converter

exclude:
  - .git/
  - .gitignore
  - node_modules/
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE