title: Fair Division Algorithms
description: Interactive educational platform for fair division algorithms

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
sass:
  style: compressed

# Collections for references (optional, if you want to use collections instead of data files)
collections:
  references:
    output: true
    permalink: /:collection/:name/

# References configuration
references:
  # Default view settings
  default_sort: "year"
  show_search: true
  show_filters: true
  show_categories: true
  
  # Citation formats supported
  citation_formats:
    - "APA"
    - "IEEE" 
    - "Chicago"
    - "MLA"
  
exclude:
  - .git/
  - .gitignore
  - node_modules/
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .vscode/
  - .idea/