# The issue: Jekyll isn't compiling SCSS to CSS

# Fix 1: Check your _config.yml
# Make sure it has proper SASS configuration:

title: Fair Division Algorithms
description: Interactive educational platform for fair division algorithms

markdown: kramdown
highlighter: rouge

# Add/fix SASS configuration
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .git/
  - .gitignore
  - node_modules/
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE