title: Fair Division Algorithms
description: Interactive educational platform developed by Amaan Khan and Dr. Ron Cytron

baseurl: "/fair-division-exercises"
url: "https://amaan-19.github.io"

# Ensure proper permalink structure
permalink: pretty

markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
highlighter: rouge

# Add/fix SASS configuration
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .git/
  - .gitignore
  - node_modules/
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE